name: CI_artifacts

on:
  pull_request:
    branches:
    - master
    - 3.x

jobs:
  collect_artifacts_Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 3
    - name: get commit message
      run: |
         export commitmsg="$(git log --format=%B -n 1 --skip 1 | head -1)"
         echo "::set-env name=commitmsg::${commitmsg}"
    - name: Build the AppImage
      if: contains( env.commitmsg, 'collect_artifacts')
      run: |
        sudo docker run -i -v "${PWD}:/MuseScore" "musescore/musescore-x86_64:latest" ./Recipe
    - name: Upload Linux AppImage artifact
      if: contains( env.commitmsg, 'collect_artifacts')
      uses: actions/upload-artifact@v1
      with:
        name: MuseScore-x86_64.AppImage
        path: ./build.release/MuseScore-x86_64.AppImage

  collect_artifacts_MacOS:
    runs-on: macos-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 3
    - name: get commit message
      run: |
         export commitmsg="$(git log --format=%B -n 1 --skip 1 | head -1)"
         echo "::set-env name=commitmsg::${commitmsg}"
    - name: Setup environment and build
      run: |
              curl -LO https://github.com/macports/macports-base/releases/download/v2.6.2/MacPorts-2.6.2-10.15-Catalina.pkg
              sudo installer -verbose -pkg MacPorts-2.6.2-10.15-Catalina.pkg -target /
              rm MacPorts-2.6.2-10.15-Catalina.pkg
              export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
              export MACOSX_DEPLOYMENT_TARGET=10.10
              echo -e "universal_target 10.10\nmacosx_deployment_target 10.10\nmacosx_sdk_version 10.10" | sudo tee -a /opt/local/etc/macports/macports.conf
              sudo port install git pkgconfig cmake
              sudo port -s install libsndfile lame portaudio jack
              export QT_SHORT_VERSION=5.9
              export QT_PATH=$HOME/qt
              export QT_MACOS=$QT_PATH/$QT_SHORT_VERSION/clang_64
              export PATH=$PATH:$QT_MACOS/bin
              echo "::set-env name=PATH::${PATH}"
    - name: Upload MacOS artifact
      uses: actions/upload-artifact@v1
      with:
        name: local
        path: /opt/local/lib