name: CI_vtests

on:
  pull_request:
    branches:
    - master

jobs:
  run_vtests:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve base commit
      run: |
        export BASEREF=$(echo ${{ github.event.pull_request.base.sha }} | head -c 8)
        if [-z "$BASEREF"]; then
        export found=0
        else
        export found=1
        fi
        echo "::set-env name=BASEREF::${BASEREF}"
        echo "::set-env name=found::${found}"
    - name: Clone repository
      if: contains( env.found, '1')
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      if: contains( env.found, '1')
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev portaudio19-dev libmp3lame-dev libsndfile1-dev libportmidi-dev
        sudo apt-get install libssl-dev libpulse-dev libfreetype6-dev libfreetype6
        sudo apt-get install libdrm-dev libgl1-mesa-dev libegl1-mesa-dev
    - name: Setup the environment
      if: contains( env.found, '1')
      run: |
        sed -i 's/travis_retry//g' build/travis/job1_Tests/environment.sh
        source build/travis/job1_Tests/environment.sh
        echo "::set-env name=PATH::${PATH}"
        echo "::set-env name=QT_PLUGIN_PATH::${QT_PLUGIN_PATH}"
        echo "::set-env name=QML2_IMPORT_PATH::${QML2_IMPORT_PATH}"
    - name: Build
      if: contains( env.found, '1')
      run: |
        make installdebug CPUS=2 PREFIX="$HOME/software" COVERAGE=ON
    - name: Build reference branch
      if: contains( env.found, '1')
      run: |
        mkdir -p "$HOME/softwarebase"
        git checkout ${{ github.event.pull_request.base.sha }}
        make installdebug CPUS=2 PREFIX="$HOME/softwarebase" COVERAGE=ON
    - name: Run reference vtests
      if: contains( env.found, '1')
      run: |
        cd vtest
        export VTEST_MSCORE="$HOME/softwarebase/bin/mscore"
        export VTEST_BROWSER=ls
        export VTEST_DIR=$(pwd)
        xvfb-run ./gen
    - name: Run vtests
      if: contains( env.found, '1')
      run: |
        git checkout -
        cd vtest
        mkdir -p compare
        find ./html -name "*-1.png" -exec mv '{}' ./compare \;
        rm -rf html 2>/dev/null
        export VTEST_MSCORE="$HOME/software/bin/mscore"
        export VTEST_BROWSER=ls
        export VTEST_DIR=$(pwd)
        xvfb-run ./gen
    - name: Compare vtests
      if: contains( env.found, '1')
      run: |
        cd vtest
        export VTEST_DIR=$(pwd)
        ./gen_compare
    - name: Upload artifact
      if: contains( env.found, '1') && contains( env.FLAG, 'true')
      uses: actions/upload-artifact@v1
      with:
        name: compare
        path: ./vtest/compare
    - name: Comment PR
      if: contains( env.found, '1') && contains( env.FLAG, 'true')
      uses: thollander/actions-comment-pull-request@1.0.0
      with:
        message: 'This is an automatic message. Your PR appears to change some of the visual tests.
          Please carefully review the new visual test results in the uploaded artifact that you can find
          [here](https://github.com/musescore/MuseScore/actions?query=workflow%3ACI_vtests)'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}